[options]
work_mode = "sys"
library = "DbusmenuGtk3"
version="0.4"
target_path = "."
min_cfg_version="0.4"

girs_directories = ["../../gir-files/"]

external_libraries = [
    "GLib",
    "Dbusmenu",
    "Gdk",
    "GdkPixbuf",
    "Gtk",
]
