[options]
work_mode = "normal"
library = "Dbusmenu"
version="0.4"
target_path = "."
min_cfg_version="0.4"

girs_directories = ["../gir-files/"]

generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
    "Dbusmenu.MenuitemProxy",
]

[[object]]
name = "Dbusmenu.Menuitem"
status = "generate"
manual_traits = ["MenuitemExtManual"]
    [[object.function]]
    pattern = "property_(set_byte_array|get_variant|set_variant)|handle_event|properties_copy"
    ignore = true
    doc_trait_name = "MenuitemExtManual"
    [[object.signal]]
    pattern = "event|property-changed"
    ignore = true
    doc_trait_name = "MenuitemExtManual"
[[object]]
name = "Dbusmenu.Client"
status = "generate"
manual_traits = ["ClientExtManual"]
    [[object.function]]
    name = "add_type_handler"
    ignore = true
    [[object.function]]
    pattern = "get_(status|text_direction)"
    ignore = true
    doc_trait_name = "ClientExtManual"
    [[object.signal]]
    pattern = "event-result|icon-theme-dirs-changed"
    ignore = true
    doc_trait_name = "ClientExtManual"
[[object]]
name = "Dbusmenu.Server"
status = "generate"
manual_traits = ["ServerExtManual"]
    [[object.function]]
    pattern = "(get|set)_(status|text_direction)"
    ignore = true
    doc_trait_name = "ServerExtManual"
    [[object.signal]]
    name = "item-property-updated"
    ignore = true
    doc_trait_name = "ServerExtManual"
