// Generated by gir (https://github.com/gtk-rs/gir @ e43ea0b348f0)
// from ../../gir-files (@ dd572419067b)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "DbusmenuGtkClient", sizeof(DbusmenuGtkClient), alignof(DbusmenuGtkClient));
    printf("%s;%zu;%zu\n", "DbusmenuGtkClientClass", sizeof(DbusmenuGtkClientClass), alignof(DbusmenuGtkClientClass));
    printf("%s;%zu;%zu\n", "DbusmenuGtkMenu", sizeof(DbusmenuGtkMenu), alignof(DbusmenuGtkMenu));
    printf("%s;%zu;%zu\n", "DbusmenuGtkMenuClass", sizeof(DbusmenuGtkMenuClass), alignof(DbusmenuGtkMenuClass));
    return 0;
}
