// Generated by gir (https://github.com/gtk-rs/gir @ e43ea0b348f0)
// from ../../gir-files (@ a25187e8c0f8)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "DbusmenuClient", sizeof(DbusmenuClient), alignof(DbusmenuClient));
    printf("%s;%zu;%zu\n", "DbusmenuClientClass", sizeof(DbusmenuClientClass), alignof(DbusmenuClientClass));
    printf("%s;%zu;%zu\n", "DbusmenuMenuitem", sizeof(DbusmenuMenuitem), alignof(DbusmenuMenuitem));
    printf("%s;%zu;%zu\n", "DbusmenuMenuitemClass", sizeof(DbusmenuMenuitemClass), alignof(DbusmenuMenuitemClass));
    printf("%s;%zu;%zu\n", "DbusmenuMenuitemProxy", sizeof(DbusmenuMenuitemProxy), alignof(DbusmenuMenuitemProxy));
    printf("%s;%zu;%zu\n", "DbusmenuMenuitemProxyClass", sizeof(DbusmenuMenuitemProxyClass), alignof(DbusmenuMenuitemProxyClass));
    printf("%s;%zu;%zu\n", "DbusmenuServer", sizeof(DbusmenuServer), alignof(DbusmenuServer));
    printf("%s;%zu;%zu\n", "DbusmenuServerClass", sizeof(DbusmenuServerClass), alignof(DbusmenuServerClass));
    printf("%s;%zu;%zu\n", "DbusmenuStatus", sizeof(DbusmenuStatus), alignof(DbusmenuStatus));
    printf("%s;%zu;%zu\n", "DbusmenuTextDirection", sizeof(DbusmenuTextDirection), alignof(DbusmenuTextDirection));
    return 0;
}
