// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod menu;
pub use self::menu::Menu;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
    pub use super::menu::MenuExt;
}
