[options]
work_mode = "sys"
library = "Dbusmenu"
version="0.4"
target_path = "."
min_cfg_version="0.4"

girs_directories = ["../../gir-files/"]

external_libraries = [
    "GLib",
    "GObject",
]

[[object]]
name = "Dbusmenu.Client"
status = "generate"
    [[object.function]]
    name = "get_icon_paths"
    manual = true
[[object]]
name = "Dbusmenu.Server"
status = "generate"
    [[object.function]]
    name = "get_icon_paths"
    manual = true
    [[object.function]]
    name = "set_icon_paths"
    manual = true
