// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

mod menuitem;
pub use self::menuitem::Menuitem;

#[doc(hidden)]
pub mod traits {
    pub use super::menuitem::MenuitemExt;
}
