// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod menuitem;
pub use self::menuitem::Menuitem;

mod menuitem_proxy;
pub use self::menuitem_proxy::MenuitemProxy;

mod server;
pub use self::server::Server;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
    pub use super::menuitem::MenuitemExt;
    pub use super::menuitem_proxy::MenuitemProxyExt;
    pub use super::server::ServerExt;
}
