// Generated by gir (https://github.com/gtk-rs/gir @ e43ea0b348f0)
// from ../../gir-files (@ 01171f6f4527)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal, clippy::upper_case_acronyms)]
#![cfg_attr(feature = "dox", feature(doc_cfg))]


mod manual;

pub use manual::*;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Enums
pub type DbusmenuStatus = c_int;
pub const DBUSMENU_STATUS_NORMAL: DbusmenuStatus = 0;
pub const DBUSMENU_STATUS_NOTICE: DbusmenuStatus = 1;

pub type DbusmenuTextDirection = c_int;
pub const DBUSMENU_TEXT_DIRECTION_NONE: DbusmenuTextDirection = 0;
pub const DBUSMENU_TEXT_DIRECTION_LTR: DbusmenuTextDirection = 1;
pub const DBUSMENU_TEXT_DIRECTION_RTL: DbusmenuTextDirection = 2;

// Constants
pub const DBUSMENU_CLIENT_PROP_DBUS_NAME: *const c_char = b"dbus-name\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_PROP_DBUS_OBJECT: *const c_char = b"dbus-object\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_PROP_GROUP_EVENTS: *const c_char = b"group-events\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_PROP_STATUS: *const c_char = b"status\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_PROP_TEXT_DIRECTION: *const c_char = b"text-direction\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_EVENT_RESULT: *const c_char = b"event-result\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_ICON_THEME_DIRS_CHANGED: *const c_char = b"icon-theme-dirs-changed\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_ITEM_ACTIVATE: *const c_char = b"item-activate\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_LAYOUT_UPDATED: *const c_char = b"layout-updated\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_NEW_MENUITEM: *const c_char = b"new-menuitem\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_SIGNAL_ROOT_CHANGED: *const c_char = b"root-changed\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_TYPES_DEFAULT: *const c_char = b"standard\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_TYPES_IMAGE: *const c_char = b"standard\0" as *const u8 as *const c_char;
pub const DBUSMENU_CLIENT_TYPES_SEPARATOR: *const c_char = b"separator\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_CHILD_DISPLAY_SUBMENU: *const c_char = b"submenu\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_DISPOSITION_ALERT: *const c_char = b"alert\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_DISPOSITION_INFORMATIVE: *const c_char = b"informative\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_DISPOSITION_NORMAL: *const c_char = b"normal\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_DISPOSITION_WARNING: *const c_char = b"warning\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_EVENT_ACTIVATED: *const c_char = b"clicked\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_EVENT_CLOSED: *const c_char = b"closed\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_EVENT_OPENED: *const c_char = b"opened\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_ICON_NAME_BLANK: *const c_char = b"blank-icon\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_ACCESSIBLE_DESC: *const c_char = b"accessible-desc\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_CHILD_DISPLAY: *const c_char = b"children-display\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_DISPOSITION: *const c_char = b"disposition\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_ENABLED: *const c_char = b"enabled\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_ICON_DATA: *const c_char = b"icon-data\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_ICON_NAME: *const c_char = b"icon-name\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_LABEL: *const c_char = b"label\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_SHORTCUT: *const c_char = b"shortcut\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_TOGGLE_STATE: *const c_char = b"toggle-state\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_TOGGLE_TYPE: *const c_char = b"toggle-type\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_TYPE: *const c_char = b"type\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_PROP_VISIBLE: *const c_char = b"visible\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SHORTCUT_ALT: *const c_char = b"Alt\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SHORTCUT_CONTROL: *const c_char = b"Control\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SHORTCUT_SHIFT: *const c_char = b"Shift\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SHORTCUT_SUPER: *const c_char = b"Super\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_ABOUT_TO_SHOW: *const c_char = b"about-to-show\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_CHILD_ADDED: *const c_char = b"child-added\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_CHILD_MOVED: *const c_char = b"child-moved\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_CHILD_REMOVED: *const c_char = b"child-removed\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_EVENT: *const c_char = b"event\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_ITEM_ACTIVATED: *const c_char = b"item-activated\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_PROPERTY_CHANGED: *const c_char = b"property-changed\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_REALIZED: *const c_char = b"realized\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_SIGNAL_SHOW_TO_USER: *const c_char = b"show-to-user\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_TOGGLE_CHECK: *const c_char = b"checkmark\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_TOGGLE_RADIO: *const c_char = b"radio\0" as *const u8 as *const c_char;
pub const DBUSMENU_MENUITEM_TOGGLE_STATE_CHECKED: c_int = 1;
pub const DBUSMENU_MENUITEM_TOGGLE_STATE_UNCHECKED: c_int = 0;
pub const DBUSMENU_MENUITEM_TOGGLE_STATE_UNKNOWN: c_int = -1;
pub const DBUSMENU_SERVER_PROP_DBUS_OBJECT: *const c_char = b"dbus-object\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_PROP_ROOT_NODE: *const c_char = b"root-node\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_PROP_STATUS: *const c_char = b"status\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_PROP_TEXT_DIRECTION: *const c_char = b"text-direction\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_PROP_VERSION: *const c_char = b"version\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_SIGNAL_ID_PROP_UPDATE: *const c_char = b"item-property-updated\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_SIGNAL_ID_UPDATE: *const c_char = b"item-updated\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_SIGNAL_ITEM_ACTIVATION: *const c_char = b"item-activation-requested\0" as *const u8 as *const c_char;
pub const DBUSMENU_SERVER_SIGNAL_LAYOUT_UPDATED: *const c_char = b"layout-updated\0" as *const u8 as *const c_char;

// Callbacks
pub type DbusmenuClientTypeHandler = Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, *mut DbusmenuMenuitem, *mut DbusmenuClient, gpointer) -> gboolean>;
pub type DbusmenuMenuitemAboutToShowCb = Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, gpointer)>;
pub type DbusmenuMenuitemBuildVariantSlot = Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, *mut *mut c_char) -> *mut glib::GVariant>;
pub type DbusmenuMenuitemForeachCb = Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, gpointer)>;

// Records
#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuClientClass {
    pub parent_class: gobject::GObjectClass,
    pub layout_updated: Option<unsafe extern "C" fn()>,
    pub root_changed: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem)>,
    pub new_menuitem: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem)>,
    pub item_activate: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, c_uint)>,
    pub event_result: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, *mut c_char, *mut glib::GVariant, c_uint, *mut glib::GError)>,
    pub icon_theme_dirs: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, gpointer, *mut glib::GError)>,
    pub reserved1: Option<unsafe extern "C" fn()>,
    pub reserved2: Option<unsafe extern "C" fn()>,
    pub reserved3: Option<unsafe extern "C" fn()>,
    pub reserved4: Option<unsafe extern "C" fn()>,
    pub reserved5: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for DbusmenuClientClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuClientClass @ {:p}", self))
         .field("parent_class", &self.parent_class)
         .field("layout_updated", &self.layout_updated)
         .field("root_changed", &self.root_changed)
         .field("new_menuitem", &self.new_menuitem)
         .field("item_activate", &self.item_activate)
         .field("event_result", &self.event_result)
         .field("icon_theme_dirs", &self.icon_theme_dirs)
         .field("reserved1", &self.reserved1)
         .field("reserved2", &self.reserved2)
         .field("reserved3", &self.reserved3)
         .field("reserved4", &self.reserved4)
         .field("reserved5", &self.reserved5)
         .finish()
    }
}

#[repr(C)]
pub struct _DbusmenuClientPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type DbusmenuClientPrivate = *mut _DbusmenuClientPrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuMenuitemClass {
    pub parent_class: gobject::GObjectClass,
    pub property_changed: Option<unsafe extern "C" fn(*mut c_char, *mut glib::GVariant)>,
    pub item_activated: Option<unsafe extern "C" fn(c_uint)>,
    pub child_added: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, c_uint)>,
    pub child_removed: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem)>,
    pub child_moved: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, c_uint, c_uint)>,
    pub realized: Option<unsafe extern "C" fn()>,
    pub buildvariant: DbusmenuMenuitemBuildVariantSlot,
    pub handle_event: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, *const c_char, *mut glib::GVariant, c_uint)>,
    pub send_about_to_show: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, DbusmenuMenuitemAboutToShowCb, gpointer)>,
    pub show_to_user: Option<unsafe extern "C" fn(*mut DbusmenuMenuitem, c_uint, gpointer)>,
    pub about_to_show: Option<unsafe extern "C" fn() -> gboolean>,
    pub event: Option<unsafe extern "C" fn(*const c_char, *mut glib::GVariant, c_uint)>,
    pub reserved1: Option<unsafe extern "C" fn()>,
    pub reserved2: Option<unsafe extern "C" fn()>,
    pub reserved3: Option<unsafe extern "C" fn()>,
    pub reserved4: Option<unsafe extern "C" fn()>,
    pub reserved5: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for DbusmenuMenuitemClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuMenuitemClass @ {:p}", self))
         .field("parent_class", &self.parent_class)
         .field("property_changed", &self.property_changed)
         .field("item_activated", &self.item_activated)
         .field("child_added", &self.child_added)
         .field("child_removed", &self.child_removed)
         .field("child_moved", &self.child_moved)
         .field("realized", &self.realized)
         .field("buildvariant", &self.buildvariant)
         .field("handle_event", &self.handle_event)
         .field("send_about_to_show", &self.send_about_to_show)
         .field("show_to_user", &self.show_to_user)
         .field("about_to_show", &self.about_to_show)
         .field("event", &self.event)
         .field("reserved1", &self.reserved1)
         .field("reserved2", &self.reserved2)
         .field("reserved3", &self.reserved3)
         .field("reserved4", &self.reserved4)
         .field("reserved5", &self.reserved5)
         .finish()
    }
}

#[repr(C)]
pub struct _DbusmenuMenuitemPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type DbusmenuMenuitemPrivate = *mut _DbusmenuMenuitemPrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuMenuitemProxyClass {
    pub parent_class: DbusmenuMenuitemClass,
    pub reserved1: Option<unsafe extern "C" fn()>,
    pub reserved2: Option<unsafe extern "C" fn()>,
    pub reserved3: Option<unsafe extern "C" fn()>,
    pub reserved4: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for DbusmenuMenuitemProxyClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuMenuitemProxyClass @ {:p}", self))
         .field("parent_class", &self.parent_class)
         .field("reserved1", &self.reserved1)
         .field("reserved2", &self.reserved2)
         .field("reserved3", &self.reserved3)
         .field("reserved4", &self.reserved4)
         .finish()
    }
}

#[repr(C)]
pub struct _DbusmenuMenuitemProxyPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type DbusmenuMenuitemProxyPrivate = *mut _DbusmenuMenuitemProxyPrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuServerClass {
    pub parent_class: gobject::GObjectClass,
    pub id_prop_update: Option<unsafe extern "C" fn(c_int, *mut c_char, *mut c_char)>,
    pub id_update: Option<unsafe extern "C" fn(c_int)>,
    pub layout_updated: Option<unsafe extern "C" fn(c_int)>,
    pub item_activation: Option<unsafe extern "C" fn(c_int, c_uint)>,
    pub reserved1: Option<unsafe extern "C" fn()>,
    pub reserved2: Option<unsafe extern "C" fn()>,
    pub reserved3: Option<unsafe extern "C" fn()>,
    pub reserved4: Option<unsafe extern "C" fn()>,
    pub reserved5: Option<unsafe extern "C" fn()>,
    pub reserved6: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for DbusmenuServerClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuServerClass @ {:p}", self))
         .field("parent_class", &self.parent_class)
         .field("id_prop_update", &self.id_prop_update)
         .field("id_update", &self.id_update)
         .field("layout_updated", &self.layout_updated)
         .field("item_activation", &self.item_activation)
         .field("reserved1", &self.reserved1)
         .field("reserved2", &self.reserved2)
         .field("reserved3", &self.reserved3)
         .field("reserved4", &self.reserved4)
         .field("reserved5", &self.reserved5)
         .field("reserved6", &self.reserved6)
         .finish()
    }
}

#[repr(C)]
pub struct _DbusmenuServerPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type DbusmenuServerPrivate = *mut _DbusmenuServerPrivate;

// Classes
#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuClient {
    pub parent: gobject::GObject,
    pub priv_: *mut DbusmenuClientPrivate,
}

impl ::std::fmt::Debug for DbusmenuClient {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuClient @ {:p}", self))
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuMenuitem {
    pub parent: gobject::GObject,
    pub priv_: *mut DbusmenuMenuitemPrivate,
}

impl ::std::fmt::Debug for DbusmenuMenuitem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuMenuitem @ {:p}", self))
         .field("parent", &self.parent)
         .field("priv_", &self.priv_)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuMenuitemProxy {
    pub parent: DbusmenuMenuitem,
    pub priv_: *mut DbusmenuMenuitemProxyPrivate,
}

impl ::std::fmt::Debug for DbusmenuMenuitemProxy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuMenuitemProxy @ {:p}", self))
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct DbusmenuServer {
    pub parent: gobject::GObject,
    pub priv_: *mut DbusmenuServerPrivate,
}

impl ::std::fmt::Debug for DbusmenuServer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("DbusmenuServer @ {:p}", self))
         .finish()
    }
}

#[link(name = "dbusmenu-glib")]
extern "C" {

    //=========================================================================
    // DbusmenuClient
    //=========================================================================
    pub fn dbusmenu_client_get_type() -> GType;
    pub fn dbusmenu_client_new(name: *const c_char, object: *const c_char) -> *mut DbusmenuClient;
    pub fn dbusmenu_client_add_type_handler(client: *mut DbusmenuClient, type_: *const c_char, newfunc: DbusmenuClientTypeHandler) -> gboolean;
    pub fn dbusmenu_client_add_type_handler_full(client: *mut DbusmenuClient, type_: *const c_char, newfunc: DbusmenuClientTypeHandler, user_data: gpointer, destroy_func: glib::GDestroyNotify) -> gboolean;
    pub fn dbusmenu_client_get_root(client: *mut DbusmenuClient) -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_client_get_status(client: *mut DbusmenuClient) -> DbusmenuStatus;
    pub fn dbusmenu_client_get_text_direction(client: *mut DbusmenuClient) -> DbusmenuTextDirection;

    //=========================================================================
    // DbusmenuMenuitem
    //=========================================================================
    pub fn dbusmenu_menuitem_get_type() -> GType;
    pub fn dbusmenu_menuitem_new() -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_menuitem_new_with_id(id: c_int) -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_menuitem_child_add_position(mi: *mut DbusmenuMenuitem, child: *mut DbusmenuMenuitem, position: c_uint) -> gboolean;
    pub fn dbusmenu_menuitem_child_append(mi: *mut DbusmenuMenuitem, child: *mut DbusmenuMenuitem) -> gboolean;
    pub fn dbusmenu_menuitem_child_delete(mi: *mut DbusmenuMenuitem, child: *mut DbusmenuMenuitem) -> gboolean;
    pub fn dbusmenu_menuitem_child_find(mi: *mut DbusmenuMenuitem, id: c_int) -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_menuitem_child_prepend(mi: *mut DbusmenuMenuitem, child: *mut DbusmenuMenuitem) -> gboolean;
    pub fn dbusmenu_menuitem_child_reorder(mi: *mut DbusmenuMenuitem, child: *mut DbusmenuMenuitem, position: c_uint) -> gboolean;
    pub fn dbusmenu_menuitem_find_id(mi: *mut DbusmenuMenuitem, id: c_int) -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_menuitem_foreach(mi: *mut DbusmenuMenuitem, callback: DbusmenuMenuitemForeachCb, user_data: gpointer);
    pub fn dbusmenu_menuitem_get_children(mi: *mut DbusmenuMenuitem) -> *mut glib::GList;
    pub fn dbusmenu_menuitem_get_id(mi: *mut DbusmenuMenuitem) -> c_int;
    pub fn dbusmenu_menuitem_get_parent(mi: *mut DbusmenuMenuitem) -> *mut DbusmenuMenuitem;
    pub fn dbusmenu_menuitem_get_position(mi: *mut DbusmenuMenuitem, parent: *mut DbusmenuMenuitem) -> c_uint;
    pub fn dbusmenu_menuitem_get_position_realized(mi: *mut DbusmenuMenuitem, parent: *mut DbusmenuMenuitem) -> c_uint;
    pub fn dbusmenu_menuitem_get_root(mi: *mut DbusmenuMenuitem) -> gboolean;
    pub fn dbusmenu_menuitem_handle_event(mi: *mut DbusmenuMenuitem, name: *const c_char, variant: *mut glib::GVariant, timestamp: c_uint);
    pub fn dbusmenu_menuitem_properties_copy(mi: *mut DbusmenuMenuitem) -> *mut glib::GHashTable;
    pub fn dbusmenu_menuitem_properties_list(mi: *mut DbusmenuMenuitem) -> *mut glib::GList;
    pub fn dbusmenu_menuitem_property_exist(mi: *const DbusmenuMenuitem, property: *const c_char) -> gboolean;
    pub fn dbusmenu_menuitem_property_get(mi: *const DbusmenuMenuitem, property: *const c_char) -> *const c_char;
    pub fn dbusmenu_menuitem_property_get_bool(mi: *const DbusmenuMenuitem, property: *const c_char) -> gboolean;
    pub fn dbusmenu_menuitem_property_get_byte_array(mi: *const DbusmenuMenuitem, property: *const c_char, nelements: *mut size_t) -> *const u8;
    pub fn dbusmenu_menuitem_property_get_int(mi: *const DbusmenuMenuitem, property: *const c_char) -> c_int;
    pub fn dbusmenu_menuitem_property_get_variant(mi: *const DbusmenuMenuitem, property: *const c_char) -> *mut glib::GVariant;
    pub fn dbusmenu_menuitem_property_remove(mi: *mut DbusmenuMenuitem, property: *const c_char);
    pub fn dbusmenu_menuitem_property_set(mi: *mut DbusmenuMenuitem, property: *const c_char, value: *const c_char) -> gboolean;
    pub fn dbusmenu_menuitem_property_set_bool(mi: *mut DbusmenuMenuitem, property: *const c_char, value: gboolean) -> gboolean;
    pub fn dbusmenu_menuitem_property_set_byte_array(mi: *mut DbusmenuMenuitem, property: *const c_char, value: *const u8, nelements: size_t) -> gboolean;
    pub fn dbusmenu_menuitem_property_set_int(mi: *mut DbusmenuMenuitem, property: *const c_char, value: c_int) -> gboolean;
    pub fn dbusmenu_menuitem_property_set_variant(mi: *mut DbusmenuMenuitem, property: *const c_char, value: *mut glib::GVariant) -> gboolean;
    pub fn dbusmenu_menuitem_send_about_to_show(mi: *mut DbusmenuMenuitem, callback: DbusmenuMenuitemAboutToShowCb, user_data: gpointer);
    pub fn dbusmenu_menuitem_set_parent(mi: *mut DbusmenuMenuitem, parent: *mut DbusmenuMenuitem) -> gboolean;
    pub fn dbusmenu_menuitem_set_root(mi: *mut DbusmenuMenuitem, root: gboolean);
    pub fn dbusmenu_menuitem_show_to_user(mi: *mut DbusmenuMenuitem, timestamp: c_uint);
    pub fn dbusmenu_menuitem_take_children(mi: *mut DbusmenuMenuitem) -> *mut glib::GList;
    pub fn dbusmenu_menuitem_unparent(mi: *mut DbusmenuMenuitem) -> gboolean;

    //=========================================================================
    // DbusmenuMenuitemProxy
    //=========================================================================
    pub fn dbusmenu_menuitem_proxy_get_type() -> GType;
    pub fn dbusmenu_menuitem_proxy_new(mi: *mut DbusmenuMenuitem) -> *mut DbusmenuMenuitemProxy;
    pub fn dbusmenu_menuitem_proxy_get_wrapped(pmi: *mut DbusmenuMenuitemProxy) -> *mut DbusmenuMenuitem;

    //=========================================================================
    // DbusmenuServer
    //=========================================================================
    pub fn dbusmenu_server_get_type() -> GType;
    pub fn dbusmenu_server_new(object: *const c_char) -> *mut DbusmenuServer;
    pub fn dbusmenu_server_get_status(server: *mut DbusmenuServer) -> DbusmenuStatus;
    pub fn dbusmenu_server_get_text_direction(server: *mut DbusmenuServer) -> DbusmenuTextDirection;
    pub fn dbusmenu_server_set_root(self_: *mut DbusmenuServer, root: *mut DbusmenuMenuitem);
    pub fn dbusmenu_server_set_status(server: *mut DbusmenuServer, status: DbusmenuStatus);
    pub fn dbusmenu_server_set_text_direction(server: *mut DbusmenuServer, dir: DbusmenuTextDirection);

}
